<?php

putenv('DISPLAY_ERRORS_DETAILS=' . true);
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_HOST=127.0.0.1');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_DBNAME=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_USER=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PASSWORD=');
putenv('CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PORT=');


